### ISSUE TITLE
Debianized pynbt

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/mcpi-packages#4]
I debianized PyNBT and mutf8 (a dependency). This could be used later with MCPIEdit debs (if any are going to be made). 

mutf8 is amd64, use wheel2deb to debianize it. https://pypi.org/project/wheel2deb/

[debs-amd64.zip](https://github.com/MCPI-Revival/mcpi-packages/files/7938138/debs-amd64.zip)

**Comment by nobody5050** [comment]
I’m not sure why you created an issue rather than a pull request if you have suggested changes for review.

**Comment by leha-code** [comment]
I will have to sign with mcpi-revivalcs gpg key which I do not have

**Comment by mobilegmYT** [comment]
You can just pull request the Deb itself in, during next run of the package script it'll be auto signed.
