### ISSUE TITLE
Repo is broken

### ISSUE THREAD

**Issue by leha-code** [MCPI-Revival/mcpi-packages#5]
It does not work for me on rpi buster. Tried that a while ago, and rn im on ubuntu so i cant reproduce. To reproduce, install this repo and try updating.

**Comment by mobilegmYT** [comment]
🤷‍♂️ works fine for me, try https://github.com/mobilegmYT/mcpi-packages-buster

**Comment by nobody5050** [comment]
Unsupported on buster, sorry!

**Comment by mobilegmYT** [comment]
*cough cough censorship* MCPI-Packages should still be able to install reborn 2.1.8 for buster, it does work for me.

**Comment by leha-code** [comment]
Still it does not work. Why not just use a single repo for all debian distros: Like in Mineshaft
https://github.com/Mineshaft-game/PPA

**Comment by mobilegmYT** [comment]
The current system we use is better, allows for more flexibility and such. If it still does not work, contact me and I'll send you my fork of the repo.

**Comment by leha-code** [comment]
well, it never worked. also it is annoying to manually reinstall mcpi-reborn on ubuntu, plz host a repo for ubuntu too

**Comment by nobody5050** [comment]
This repo works for Ubuntu, it’s what I use. You can also use the flatpak
